// Datos de prueba para desarrollo local sin Supabase
import type { Recurso } from '@/types/database'

export const MOCK_RECURSOS: Recurso[] = [
  {
    id: '1',
    titulo: 'Signos de puntuación — ejercicios',
    resumen: 'Ficha de trabajo con ejercicios sobre el uso del punto, la coma y el punto y coma para alumnos de 3er grado.',
    grados: ['3ro'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Ortografía',
    tipo_recurso: 'Actividad',
    formato: 'Documento',
    editable: true,
    estado: 'publicado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'cyntia',
    autor_nombre: 'Cyntia',
    descargas: 12,
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-03-15T10:00:00Z',
  },
  {
    id: '2',
    titulo: 'Uso de la coma — evaluación',
    resumen: 'Evaluación escrita sobre reglas de uso de la coma: enumeración, vocativo y aclaraciones.',
    grados: ['3ro'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Ortografía',
    tipo_recurso: 'Evaluación',
    formato: 'Documento',
    editable: false,
    estado: 'publicado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'ana',
    autor_nombre: 'Ana R.',
    descargas: 8,
    created_at: '2025-11-20T10:00:00Z',
    updated_at: '2025-11-20T10:00:00Z',
  },
  {
    id: '3',
    titulo: 'Puntuación en cuentos cortos',
    resumen: 'Actividad donde los alumnos deben colocar los signos de puntuación faltantes en fragmentos de cuentos.',
    grados: ['3ro', '4to'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Ortografía',
    tipo_recurso: 'Actividad',
    formato: 'Documento',
    editable: true,
    estado: 'publicado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'cyntia',
    autor_nombre: 'Cyntia',
    descargas: 3,
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
  },
  {
    id: '4',
    titulo: 'El punto y seguido vs. punto y aparte',
    resumen: 'Presentación con explicación visual de la diferencia entre punto y seguido y punto y aparte, con ejemplos.',
    grados: ['3ro'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Ortografía',
    tipo_recurso: 'Presentación',
    formato: 'Presentación slides',
    editable: true,
    estado: 'destacado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'laura',
    autor_nombre: 'Laura M.',
    descargas: 15,
    created_at: '2026-01-08T10:00:00Z',
    updated_at: '2026-01-08T10:00:00Z',
  },
  {
    id: '5',
    titulo: 'Planificación anual — Gramática 4to',
    resumen: 'Planificación anual de contenidos de gramática para 4to grado, organizada por trimestre.',
    grados: ['4to'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Gramática',
    tipo_recurso: 'Planificación',
    formato: 'Documento',
    editable: true,
    estado: 'publicado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'cyntia',
    autor_nombre: 'Cyntia',
    descargas: 20,
    created_at: '2026-02-28T10:00:00Z',
    updated_at: '2026-02-28T10:00:00Z',
  },
  {
    id: '6',
    titulo: 'Comprensión lectora — El principito (cap. 1-5)',
    resumen: 'Guía de comprensión lectora con preguntas de inferencia y análisis sobre los primeros capítulos de El Principito.',
    grados: ['5to', '6to'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Comprensión lectora',
    tipo_recurso: 'Actividad',
    formato: 'Documento',
    editable: true,
    estado: 'publicado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'maria',
    autor_nombre: 'María L.',
    descargas: 25,
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
  },
  {
    id: '7',
    titulo: 'Rúbrica de producción escrita',
    resumen: 'Rúbrica con criterios de evaluación para textos narrativos: coherencia, cohesión, ortografía y creatividad.',
    grados: ['4to', '5to', '6to'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Producción escrita',
    tipo_recurso: 'Rúbrica',
    formato: 'Documento',
    editable: true,
    estado: 'destacado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'cyntia',
    autor_nombre: 'Cyntia',
    descargas: 18,
    created_at: '2026-03-10T10:00:00Z',
    updated_at: '2026-03-10T10:00:00Z',
  },
  {
    id: '8',
    titulo: 'Clases de palabras — juego interactivo',
    resumen: 'Juego en Wordwall para clasificar sustantivos, adjetivos y verbos arrastrando las palabras.',
    grados: ['2do', '3ro'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Gramática',
    tipo_recurso: 'Actividad',
    formato: 'Juego / Interactivo',
    editable: false,
    estado: 'publicado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: 'https://wordwall.net/ejemplo',
    texto_extraido: null,
    subido_por: 'ana',
    autor_nombre: 'Ana R.',
    descargas: 30,
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-01-20T10:00:00Z',
  },
  {
    id: '9',
    titulo: 'Lectura en voz alta — guía docente',
    resumen: 'Guía con estrategias para la lectura en voz alta: selección de textos, modulación, preguntas disparadoras.',
    grados: ['1ro', '2do', '3ro'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Oralidad',
    tipo_recurso: 'Teoría / Marco',
    formato: 'Documento',
    editable: false,
    estado: 'publicado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'cyntia',
    autor_nombre: 'Cyntia',
    descargas: 7,
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-02-15T10:00:00Z',
  },
  {
    id: '10',
    titulo: 'Vocabulario — campos semánticos',
    resumen: 'Actividad para agrupar palabras por campos semánticos: animales, alimentos, profesiones, emociones.',
    grados: ['1ro', '2do'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Vocabulario',
    tipo_recurso: 'Actividad',
    formato: 'Documento',
    editable: true,
    estado: 'publicado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'laura',
    autor_nombre: 'Laura M.',
    descargas: 5,
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: '11',
    titulo: 'Plan lector — selección 1er trimestre',
    resumen: 'Listado de libros recomendados para el plan lector del primer trimestre, con ficha de cada libro.',
    grados: ['3ro', '4to'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Plan lector',
    tipo_recurso: 'Planificación',
    formato: 'Documento',
    editable: true,
    estado: 'publicado',
    idioma: 'es',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'cyntia',
    autor_nombre: 'Cyntia',
    descargas: 22,
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-01T10:00:00Z',
  },
  {
    id: '12',
    titulo: 'Writing prompts — Creative stories',
    resumen: 'Set of creative writing prompts for English class. Students write short stories based on visual cues.',
    grados: ['5to', '6to'],
    area: 'Prácticas del Lenguaje',
    eje_tematico: 'Producción escrita',
    tipo_recurso: 'Actividad',
    formato: 'Documento',
    editable: true,
    estado: 'publicado',
    idioma: 'en',
    archivo_drive_id: null,
    archivo_url: null,
    thumbnail_url: null,
    link_editable: null,
    texto_extraido: null,
    subido_por: 'maria',
    autor_nombre: 'María L.',
    descargas: 10,
    created_at: '2026-03-05T10:00:00Z',
    updated_at: '2026-03-05T10:00:00Z',
  },
]
