-- LUMEN v0.7e — Copiloto v2: bloque tablero_juego (juegos de mesa serpenteados)
-- Ejecutar DESPUÉS de v07, v07b, v07c, v07d. Idempotente.
--
-- Actualiza los prompts de adapt y similar para que reconozcan y usen
-- el bloque tablero_juego cuando el recurso original sea un juego de tablero
-- (carrera de palabras, dado, ruleta, ludo educativo, etc.)

update prompt_templates set layer_task = E'Recibís un recurso pedagógico y debés adaptarlo según los ejes que solicita la docente.\n\nIMPORTANTE: si en el mensaje del usuario viene una imagen o PDF del recurso original, ese es el material real que usa el docente. Hacé DOS cosas con él:\n\n1) MIRÁ SU FORMATO VISUAL y reproducí algo análogo en el output. Si el original tiene cuadrículas, usá `cuadricula_escritura`. Si tiene líneas en blanco, usá `lineas_respuesta`. Si es una tabla para completar, usá `tabla_llenar`. Si tiene opciones para marcar, usá `opcion_marcar`. Si tiene espacios para dibujar, usá `recuadro_dibujar`. **Si es un TABLERO DE JUEGO (carrera de palabras, juego de la oca, ludo educativo, tablero con casilleros numerados), usá `tablero_juego`** — no lo conviertas en tabla de filas/columnas.\n\n2) EXTRAÉ UN PERFIL VISUAL (style_profile) que aplicaremos al PDF para que se sienta del mismo set. Mirá:\n   - paleta.primario: color hex predominante del original (el color del header/títulos/acentos). Ej #2E6EA6, #8B2252.\n   - paleta.secundario: segundo color si lo hay, sino omitir.\n   - densidad: "compacta" (mucho contenido por hoja, poco aire), "media" (balanceada), "espaciosa" (mucho aire blanco).\n   - tipografia_estilo: "serif", "sans" (palo seco), "redondeada" (tipo Comic Sans, Andika), "manuscrita".\n   - tono_visual: "formal" (escolar tradicional), "amigable" (cálido), "ludico" (colorido y divertido, primer ciclo).\n\nEl docente debe poder imprimir tu output y usarlo directo en el aula, sintiendo que es continuación natural del material original.\n\nEjes posibles que vienen en input_params:\n- grado_destino (1 a 7): ajustá vocabulario, complejidad conceptual y extensión. Mantené el área y el eje temático originales.\n- dua_level (estandar | leve | profunda | enriquecimiento): aplicá las pautas DUA según el nivel pedido.\n- modalidad (presencial | domiciliario | virtual_asincronico): adaptá la consigna a esa modalidad.\n- tiempo_min (entero): condensá o expandí según los minutos disponibles.\n\nBLOQUES VISUALES disponibles:\n- cuadricula_escritura: palabra + casilleros vacíos para escribir letra por letra.\n- lineas_respuesta: líneas en blanco para escribir a mano.\n- recuadro_dibujar: caja vacía para que el chico dibuje.\n- tabla_llenar: tabla con encabezados pero celdas vacías para completar.\n- opcion_marcar: opciones con círculo/casilla para marcar.\n- **tablero_juego: tablero serpenteado tipo Oca con casilleros numerados. Soporta casilleros especiales (salida, meta, avanzar, retroceder, especial). Ideal para juegos de vocabulario, operaciones matemáticas, efemérides, geografía.**\n\nRegla clave: NO uses imagen_sugerida ni tabla si lo correcto es un bloque visual estructurado.\n\nDocumentá qué cambios hiciste en cambios_realizados[]. derived_from debe apuntar al recurso original. Si NO hay archivo original adjunto, omití style_profile.'
where slug = 'adapt';

update prompt_templates set layer_task = E'Recibís una actividad existente como inspiración y debés generar una o más actividades nuevas del mismo tipo pedagógico.\n\nIMPORTANTE: si viene una imagen o PDF del original:\n1) Mantené el formato visual: cuadrículas, líneas, tablas, opciones, **tableros de juego**. Las nuevas tienen lo mismo que la original.\n2) Extraé style_profile (paleta.primario en hex, densidad, tipografia_estilo, tono_visual) para que las nuevas fichas se sientan del mismo set.\n\nNO copies el original. Tomá su estructura, su tipo de actividad y su nivel de exigencia, y generá hermanas.\n\nVariaciones que pueden venir en input_params:\n- cantidad (1, 3, 5): cuántas generar\n- mismo_contenido (bool): si true, mismo tema; si false, sugerí otro relacionado\n- ajuste_grado (mismo | mas_uno | menos_uno)\n- dificultad (mas_facil | igual | mas_desafiante)\n- formato (mismo | cambiar)\n\nBLOQUES VISUALES disponibles: cuadricula_escritura, lineas_respuesta, recuadro_dibujar, tabla_llenar, opcion_marcar, **tablero_juego**.\n\nSi el original es un juego de tablero (carrera, ludo educativo, oca), la actividad similar debe ser TAMBIÉN un tablero de juego con bloque `tablero_juego`, no una tabla.\n\nCada actividad debe poder usarse en forma independiente. En diferencias_clave explicá en UNA línea qué la distingue del original. Si NO hay archivo original adjunto, omití style_profile.'
where slug = 'similar';
