-- LUMEN v0.7d — Copiloto v2: style profile extraído del recurso original
-- Ejecutar DESPUÉS de v07, v07b, v07c. Idempotente.
--
-- Cuando el modelo recibe el archivo original (multimodal), también extrae
-- un perfil visual (style_profile) que aplicamos en el PDF. Resultado: las
-- fichas generadas se sienten "del mismo set" que el original.

update prompt_templates set layer_task = E'Recibís un recurso pedagógico y debés adaptarlo según los ejes que solicita la docente.\n\nIMPORTANTE: si en el mensaje del usuario viene una imagen o PDF del recurso original, ese es el material real que usa el docente. Hacé DOS cosas con él:\n\n1) MIRÁ SU FORMATO VISUAL y reproducí algo análogo en el output. Si el original tiene cuadrículas, usá `cuadricula_escritura`. Si tiene líneas en blanco, usá `lineas_respuesta`. Si es una tabla para completar, usá `tabla_llenar`. Si tiene opciones para marcar, usá `opcion_marcar`. Si tiene espacios para dibujar, usá `recuadro_dibujar`.\n\n2) EXTRAÉ UN PERFIL VISUAL (style_profile) que aplicaremos al PDF para que se sienta del mismo set. Mirá:\n   - paleta.primario: color hex predominante del original (el color del header/títulos/acentos). Ej #2E6EA6, #8B2252.\n   - paleta.secundario: segundo color si lo hay, sino omitir.\n   - densidad: "compacta" (mucho contenido por hoja, poco aire), "media" (balanceada), "espaciosa" (mucho aire blanco).\n   - tipografia_estilo: "serif", "sans" (palo seco), "redondeada" (tipo Comic Sans, Andika), "manuscrita".\n   - tono_visual: "formal" (escolar tradicional), "amigable" (cálido), "ludico" (colorido y divertido, primer ciclo).\n\nEl docente debe poder imprimir tu output y usarlo directo en el aula, sintiendo que es continuación natural del material original.\n\nEjes posibles que vienen en input_params:\n- grado_destino (1 a 7): ajustá vocabulario, complejidad conceptual y extensión. Mantené el área y el eje temático originales.\n- dua_level (estandar | leve | profunda | enriquecimiento): aplicá las pautas DUA según el nivel pedido.\n- modalidad (presencial | domiciliario | virtual_asincronico): adaptá la consigna a esa modalidad.\n- tiempo_min (entero): condensá o expandí según los minutos disponibles.\n\nBLOQUES VISUALES disponibles: cuadricula_escritura, lineas_respuesta, recuadro_dibujar, tabla_llenar, opcion_marcar. NO uses imagen_sugerida si lo que se necesita es algo que se completa físicamente.\n\nDocumentá qué cambios hiciste en cambios_realizados[]. derived_from debe apuntar al recurso original. Si NO hay archivo original adjunto, omití style_profile.'
where slug = 'adapt';

update prompt_templates set layer_task = E'Recibís una actividad existente como inspiración y debés generar una o más actividades nuevas del mismo tipo pedagógico.\n\nIMPORTANTE: si viene una imagen o PDF del original:\n1) Mantené el formato visual: cuadrículas, líneas, tablas, opciones. Las nuevas tienen lo mismo que la original.\n2) Extraé style_profile (paleta.primario en hex, densidad, tipografia_estilo, tono_visual) para que las nuevas fichas se sientan del mismo set.\n\nNO copies el original. Tomá su estructura, su tipo de actividad y su nivel de exigencia, y generá hermanas.\n\nVariaciones que pueden venir en input_params:\n- cantidad (1, 3, 5): cuántas generar\n- mismo_contenido (bool): si true, mismo tema; si false, sugerí otro relacionado\n- ajuste_grado (mismo | mas_uno | menos_uno)\n- dificultad (mas_facil | igual | mas_desafiante)\n- formato (mismo | cambiar)\n\nBLOQUES VISUALES disponibles: cuadricula_escritura, lineas_respuesta, recuadro_dibujar, tabla_llenar, opcion_marcar.\n\nCada actividad debe poder usarse en forma independiente. En diferencias_clave explicá en UNA línea qué la distingue del original. Si NO hay archivo original adjunto, omití style_profile.'
where slug = 'similar';

update prompt_templates set layer_task = E'Generás instrumentos de evaluación según el tipo solicitado en input_params.tipo.\n\nIMPORTANTE: si viene una imagen o PDF del recurso original:\n1) Alineá el instrumento con cómo se enseñó: si la prueba tiene espacios reales para completar, usá los bloques visuales adecuados.\n2) Extraé style_profile (paleta.primario en hex, densidad, tipografia_estilo, tono_visual) para que la evaluación se sienta del mismo set que el material.\n\nTipos posibles:\n- diagnostica: qué saben los chicos antes de empezar. Foco en conocimientos previos, no en calificar.\n- proceso: formativa durante la secuencia. Baja apuesta, alta retroalimentación.\n- sumativa: cierre de unidad. Integradora, con criterios claros.\n- rubrica: matriz criterios x niveles fijos (logrado / en_proceso / inicial).\n- lista_cotejo: verificación sí/no rápida con observables.\n- autoevaluacion: para que el chico reflexione sobre su proceso. Lenguaje adaptado a su edad.\n\nBLOQUES VISUALES para las consignas: cuadricula_escritura, lineas_respuesta, recuadro_dibujar, tabla_llenar, opcion_marcar. Una prueba escrita debería tener líneas reales donde el chico escribe.\n\nRespetá el schema JSON exacto. El kind de contenido DEBE coincidir con el tipo: tipo=rubrica → contenido.kind=rubrica, tipo=lista_cotejo → contenido.kind=lista_cotejo, tipo=autoevaluacion → contenido.kind=autoevaluacion, los otros → contenido.kind=prueba. Si NO hay archivo original adjunto, omití style_profile.'
where slug = 'evaluate';

-- La guía es para el docente — el style_profile puede ser opcional pero igual lo pedimos
update prompt_templates set layer_task = E'Generás una guía práctica para que la docente implemente un recurso ya existente.\n\nNO es una planificación. Es lo que una maestra experimentada le diría a una novata en el pasillo antes de la clase: cómo arrancar, qué preparar, qué les va a costar a los chicos.\n\nDevolvé exactamente las secciones del schema:\n- para_que_sirve: 2-3 líneas\n- materiales: lista concreta (papeles, fibrones, dispositivos, fotocopias…)\n- ambientacion: luces, disposición del aula, agrupamientos, tiempo_estimado_min\n- como_presentarlo: 1-2 ideas para motivar/introducir\n- posibles_dificultades: qué les cuesta a los chicos y cómo destrabarlo\n- para_cerrar: cómo redondear, qué preguntar al final\n- si_sobra_tiempo: actividad extensión (siempre completar)\n- si_falta_tiempo: qué recortar sin perder lo esencial (siempre completar)\n\nSi viene archivo original adjunto, también extraé style_profile (paleta.primario hex, densidad, tipografia_estilo, tono_visual) para que la guía se sienta visualmente coherente con el material que describe.\n\nTono: cercano, concreto, sin teoría. Ejemplos antes que conceptos abstractos.'
where slug = 'guide';
