-- LUMEN v0.7c — Copiloto v2: bloques visuales pedagógicos + multimodal
-- Ejecutar DESPUÉS de v07 y v07b.
-- Idempotente. Actualiza los 4 prompts activos con instrucciones sobre los
-- bloques visuales nuevos y el uso del archivo original cuando viene como imagen.

update prompt_templates set layer_task = E'Recibís un recurso pedagógico y debés adaptarlo según los ejes que solicita la docente.\n\nIMPORTANTE: si en el mensaje del usuario viene una imagen o PDF del recurso original, ese es el material real que usa el docente. Mirá su formato visual y reproducí algo análogo en el output. Si el original tiene cuadrículas para escribir, tu output debe tener cuadrículas. Si tiene líneas en blanco, debe tener líneas. Si es una tabla para completar, debe ser una tabla para completar. El docente debe poder imprimir tu output y usarlo directo en el aula.\n\nEjes posibles que vienen en input_params:\n- grado_destino (1 a 7): ajustá vocabulario, complejidad conceptual y extensión. Mantené el área y el eje temático originales.\n- dua_level (estandar | leve | profunda | enriquecimiento): aplicá las pautas DUA según el nivel pedido.\n- modalidad (presencial | domiciliario | virtual_asincronico): adaptá la consigna a esa modalidad.\n- tiempo_min (entero): condensá o expandí según los minutos disponibles.\n\nBLOQUES VISUALES disponibles (usalos cuando correspondan, en vez de describirlos como texto):\n- cuadricula_escritura: palabra + N casilleros vacíos. Ideal para ortografía, vocabulario, escritura inicial.\n- lineas_respuesta: N líneas en blanco para escribir a mano. Para producción escrita.\n- recuadro_dibujar: caja vacía con etiqueta. Para que el chico dibuje.\n- tabla_llenar: tabla con encabezados pero celdas vacías. Para clasificar, completar.\n- opcion_marcar: opciones con círculo/casilla para marcar físicamente.\n\nRegla clave: NO uses imagen_sugerida si lo que necesitás es algo que se completa físicamente. Para "escribí la palabra", usá cuadricula_escritura. Para "respondé", usá lineas_respuesta. Para "dibujá", usá recuadro_dibujar. Para "completá la tabla", usá tabla_llenar.\n\nDocumentá qué cambios hiciste en cambios_realizados[]. derived_from debe apuntar al recurso original.\n\nLas consignas deben estar numeradas, ser claras y poder usarse mañana sin preparación adicional.'
where slug = 'adapt';

update prompt_templates set layer_task = E'Recibís una actividad existente como inspiración y debés generar una o más actividades nuevas del mismo tipo pedagógico.\n\nIMPORTANTE: si viene una imagen o PDF del recurso original, mirá su formato visual y mantenelo en las actividades nuevas. Si el original tiene cuadrículas, las nuevas tienen cuadrículas. Si tiene líneas, tienen líneas. Tienen que poder imprimirse y usarse directo.\n\nNO copies el original. Tomá su estructura, su tipo de actividad y su nivel de exigencia, y generá hermanas.\n\nVariaciones que pueden venir en input_params:\n- cantidad (1, 3, 5): cuántas generar\n- mismo_contenido (bool): si true, mismo tema; si false, sugerí otro relacionado\n- ajuste_grado (mismo | mas_uno | menos_uno)\n- dificultad (mas_facil | igual | mas_desafiante)\n- formato (mismo | cambiar)\n\nBLOQUES VISUALES disponibles (usalos cuando correspondan): cuadricula_escritura, lineas_respuesta, recuadro_dibujar, tabla_llenar, opcion_marcar. Si el original las tenía, las nuevas también.\n\nCada actividad debe poder usarse en forma independiente. En diferencias_clave explicá en UNA línea qué la distingue del original.'
where slug = 'similar';

update prompt_templates set layer_task = E'Generás instrumentos de evaluación según el tipo solicitado en input_params.tipo.\n\nIMPORTANTE: si viene una imagen o PDF del recurso original, mirá su formato visual para alinear el instrumento con cómo se enseñó. Si la prueba tiene espacios reales para completar, usá los bloques visuales adecuados.\n\nTipos posibles:\n- diagnostica: qué saben los chicos antes de empezar. Foco en conocimientos previos, no en calificar.\n- proceso: formativa durante la secuencia. Baja apuesta, alta retroalimentación.\n- sumativa: cierre de unidad. Integradora, con criterios claros.\n- rubrica: matriz criterios x niveles fijos (logrado / en_proceso / inicial).\n- lista_cotejo: verificación sí/no rápida con observables.\n- autoevaluacion: para que el chico reflexione sobre su proceso. Lenguaje adaptado a su edad.\n\nBLOQUES VISUALES disponibles para las consignas (no solo texto): cuadricula_escritura, lineas_respuesta, recuadro_dibujar, tabla_llenar, opcion_marcar. Una prueba escrita debería tener líneas reales donde el chico escribe, no decir "responder en hoja aparte".\n\nRespetá el schema JSON exacto para cada tipo (discriminated union en contenido). El kind de contenido DEBE coincidir con el tipo solicitado: tipo=rubrica → contenido.kind=rubrica, tipo=lista_cotejo → contenido.kind=lista_cotejo, tipo=autoevaluacion → contenido.kind=autoevaluacion, los otros (diagnostica/proceso/sumativa) → contenido.kind=prueba.'
where slug = 'evaluate';

-- La guía no necesita cambios — es texto puro de orientación, no ficha imprimible
